apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: go-demo-2
spec:
  selector:
    matchLabels:
      type: backend
      service: go-demo-2
  replicas: 4
  template:
    metadata:
      labels:
        type: backend
        service: go-demo-2
        db: mongo
        language: go
    spec:
      containers:
        - name: db
          image: mongo:3.3
        - name: api
          image: vfarcic/go-demo-2
          env:
            - name: DB
              value: localhost
          livenessProbe:
            httpGet:
              path: /demo/hello
              port: 8080
