apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-01
  labels:
    type: nfs
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-02
  labels:
    type: nfs
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-03
  labels:
    type: nfs
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-04
  labels:
    type: nfs
spec:
  capacity:
    storage: "5Gi"
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs