apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: jenkins
spec:
  resources:
    requests:
      storage: "1Gi"
  storageClassName: nfs-01
  accessModes:
    - ReadWriteOnce